name: Kodkod frontend deploy

on:
  push:
    branches:
      - develop
      - sandbox
  pull_request:
    branches:
      - master
      - develop
  release:
    types: [released]

env:
  NODE_VERSION: 20.11.0
  CACHE_PACKAGE_MANAGER: 'yarn'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v4

      - name: Node.js ${{ env.NODE_VERSION }} setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE_PACKAGE_MANAGER }}

      - name: Dependencies installation
        run: yarn install --frozen-lockfile

      - name: Format check
        run: yarn format-check

      - name: ESLint check
        run: yarn eslint-check

      - name: TypeScript check
        run: yarn ts-check

  build:
    if: ${{ github.ref_name == 'develop' || startsWith(github.head_ref, 'release/v') || (github.event_name == 'release' && ! github.event.release.prerelease) }}
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v4

      - name: Node.js ${{ env.NODE_VERSION }} setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE_PACKAGE_MANAGER }}

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Building for development
        if: github.base_ref == 'develop'
        run: |
          echo VITE_API_BASE_URL=${{ vars.DEV_API_BASE_URL }} >> .env.staging
          yarn build --mode staging

      - name: Building for production
        if: github.base_ref == 'master'
        run: |
          echo VITE_API_BASE_URL=${{ vars.PROD_API_BASE_URL }} >> .env.production
          yarn build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy-dev:
    if: github.ref_name == 'develop' || startsWith(github.head_ref, 'release/v')
    name: app-dev.kodkod.cl
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./ s3://${{ secrets.DEVELOPMENT_DNS }}

      - name: Clear distribution cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_DISTRIBUTION_ID }} --paths "/*"

  deploy-prod:
    if: ${{ github.event_name == 'release' && ! github.event.release.prerelease }}
    name: app.kodkod.cl
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./ s3://app.kodkod.cl

      - name: Clear distribution cache
        run: aws cloudfront create-invalidation --distribution-id E371T76OJMZGY9 --paths "/*"
