name: Kodkod frontend deploy

on:
  push:
    branches-ignore:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed

env:
  NODE_VERSION: 18.3.0
  CACHE_PACKAGE_MANAGER: 'yarn'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Node.js ${{ env.NODE_VERSION }} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE_PACKAGE_MANAGER }}

      - name: Dependencies installation
        run: yarn install --frozen-lockfile

      - name: Format check
        run: yarn format-check

      - name: ESLint check
        run: yarn eslint-check

      - name: TypeScript check
        run: yarn ts-check

  build:
    name: Build
    if: github.event.pull_request.merged == true
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Node.js ${{ env.NODE_VERSION }} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE_PACKAGE_MANAGER }}

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Building for development
        if: github.base_ref == 'develop'
        run: yarn build -- --mode staging

      - name: Building for production
        if: github.base_ref == 'main'
        run: yarn build

      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  deploy:
    name: app.kodkod.cl
    if: github.base_ref == 'main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./ s3://${{ secrets.PRODUCTION_DNS }}

      - name: Clear distribution cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_DISTRIBUTION_ID }} --paths "/*"

  deploy-dev:
    name: app-dev.kodkod.cl
    if: github.base_ref == 'develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./ s3://${{ secrets.DEVELOPMENT_DNS }}

      - name: Clear distribution cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_DISTRIBUTION_ID }} --paths "/*"
