name: Kodkod frontend deploy

on:
  pull_request:
    branches:
      - development
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }} setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Installing dependencies
        run: npx yarn install

      - name: Building
        run: npx yarn build

      - name: Saving build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deploy-dev:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Get build
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to S3 bucket
        run: aws s3 sync dist s3://${{ secrets.DEVELOPMENT_DNS }}

      - name: Clear distribution cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_DISTRIBUTION_ID }} --paths "/*"
